### ISSUE TITLE
Add new binding for FMOD

### ISSUE THREAD

**Issue by lebedec** [rust-gamedev/arewegameyet#475]
The one listed now [fmod](https://crates.io/crates/libfmod) is for old FMOD Ex version.

A new unofficial binding [libfmod](https://crates.io/crates/libfmod) supports new releases of FMOD Engine / Studio. 

```toml
[[items]]
name = "libfmod"
source = "crates"
categories = ["audio"]
```
